{
 "title": "Robot Shop Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(kube_service_info{namespace=\"robot-shop\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latência",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service=~\"$service\"}[1m])) by (le, service))",
     "legendFormat": "{{service}} - p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{service=~\"$service\"}[1m])) by (le, service))",
     "legendFormat": "{{service}} - p90"
    }
   ]
  },
  {
   "title": "Tráfego",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Disponibilidade",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\nsum(increase(http_request_duration_seconds_count{service=~\"$service\", code=~\"[45].*\"}[1m])) by (service) or vector(0)\n/\nsum(increase(http_request_duration_seconds_count{service=~\"$service\"}[1m])) by (service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Saturação - Consumo de Memória",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate (container_memory_usage_bytes{image!=\"\", container=~\"$service\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Saturação - Consumo de CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"$service\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}