apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    service: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      service: cart
  template:
    metadata:
      labels:
        service: cart
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '8080'  
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: cart
        image: {{ .Values.ciandt.image.repo }}/rs-cart:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # agent networking access
        env:
          - name: DECREASE_AVAILABILITY
            value: "false"
          - name: PERCENT_DECREASE_AVAILABILITY
            value: "10"
          - name: INCREASE_LATENCY
            value: "false"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
