apiVersion: v1
kind: LimitRange
metadata:
  name: robot-shop-limit-range
spec:
  limits:
  - default:
      cpu: 200m
      memory: 200Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    type: Container